In [2]:
import numpy as np
import pandas as pd
import os

In [7]:
path=os.path.expanduser("~\.kaggle\competitions\liberty-mutual-fire-peril")


'C:\\Users\\Wesle\\.kaggle\\competitions\\liberty-mutual-fire-peril\\train.csv'

In [8]:
# train_y_path=os.path.expanduser("C:\Users\Wesle\.kaggle\competitions\liberty-mutual-fire-peril")
train=pd.read_csv(path+"\\train.csv")

C:\Wesley_Tao\6.Software\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [9]:
train.head()

id  target var1 var2 var3 var4 var5 var6 var7 var8      ...       \
0   1     0.0    Z    Z    Z   N1    Z    Z    3    1      ...        
1   2     0.0    Z    Z    Z   C1    Z    Z    3    2      ...        
2   3     0.0    3    Z    4   J3    B    B    2    4      ...        
3   4     0.0    3    Z    4   H1    B    Z    3    4      ...        
4   5     0.0    Z    Z    Z   H1    Z    Z    2    4      ...        

  weatherVar227  weatherVar228  weatherVar229  weatherVar230  weatherVar231  \
0      0.170351            0.0        0.00000       0.000000       1.117353   
1      0.266173            0.0       27.50823       0.000000       3.828979   
2      0.979517            0.0        0.00000       0.456134       0.098790   
3      0.308761            0.0        0.00000       4.349042       0.401975   
4      2.171972            0.0        0.00000       0.514990       0.516095   

   weatherVar232  weatherVar233  weatherVar234  weatherVar235 weatherVar236  
0       1.215303       0.112556       2.355737       0.404655      0.138667  
1       1.036739       0.033052       0.856632       0.231232      0.742199  
2       1.076535       0.566352       0.696013       0.693695      0.070654  
3       0.340631       0.290147       0.000000       0.000000      0.090332  
4       1.016120       1.313732       1.338487       2.948202      0.816485  

[5 rows x 302 columns]

In [12]:
from sklearn.preprocessing import OneHotEncoder

In [13]:
enc = OneHotEncoder()
enc.fit([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]])  

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [14]:
enc.n_values_

array([2, 3, 4])

In [15]:
enc.feature_indices_

array([0, 2, 5, 9], dtype=int32)

In [18]:
enc.fit_transform([[0, 1, 1]]).toarray()


array([[ 1.,  1.,  1.]])